@extends('layouts.default')
@section('contenu')
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>
    <h1>ACCUEIL</h1>

@endsection